'use client'

import * as React from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ChevronDownIcon, SaveIcon, SettingsIcon } from 'lucide-react'
import { toast } from 'sonner'
import { AdminMarkdownEditor } from '@/components/Admin/markdown-editor'
import { useAdminAuth } from '@/components/Admin/auth-provider'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import {
  createPostAPI,
  getPostByIdAPI,
  queryAllByTypeAPI,
  queryLabelListAPI,
  updatePostAPI,
} from '@/lib/admin/api'
import { cn } from '@/lib/utils'
import type { LabelVO } from '@/types/admin/label'
import type { PostReq } from '@/types/admin/post'

const emptyPost = (): PostReq => ({
  created_at: new Date().toISOString(),
  title: '',
  content: '',
  description: '',
  alias: '',
  category_id: '',
  tags_id: [],
  is_publish: true,
  is_top: false,
  thumbnail: '',
})

function toDatetimeLocal(value?: string) {
  if (!value) return ''
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return ''
  return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
}

export function PostEditorPage({ mode }: { mode: 'create' | 'edit' }) {
  const router = useRouter()
  const params = useParams<{ id?: string }>()
  const { request } = useAdminAuth()
  const [postForm, setPostForm] = React.useState<PostReq>(emptyPost)
  const [categories, setCategories] = React.useState<LabelVO[]>([])
  const [tags, setTags] = React.useState<LabelVO[]>([])
  const [pending, setPending] = React.useState(false)

  const postId = params.id
  const selectedTags = tags.filter(tag => postForm.tags_id?.includes(tag.id))
  const selectedTagText = selectedTags.length
    ? selectedTags.map(tag => tag.name).join('、')
    : '请选择标签'
  const submitText = mode === 'create' ? (pending ? '发布中...' : '发布') : (pending ? '保存中...' : '保存')

  const updateForm = <K extends keyof PostReq>(key: K, value: PostReq[K]) => {
    setPostForm(current => ({ ...current, [key]: value }))
  }

  React.useEffect(() => {
    Promise.all([
      queryAllByTypeAPI(request, 'category'),
      queryLabelListAPI(request, { page_no: 1, page_size: 100, label_type: 'tag' }),
    ])
      .then(([categoryRes, tagRes]) => {
        setCategories(categoryRes.data)
        setTags(tagRes.data.list)
      })
      .catch(error => toast.error(error instanceof Error ? error.message : '加载分类标签失败'))
  }, [request])

  React.useEffect(() => {
    if (mode !== 'edit' || !postId) return
    getPostByIdAPI(request, postId)
      .then(response => {
        setPostForm({
          ...emptyPost(),
          ...response.data,
        })
      })
      .catch(error => toast.error(error instanceof Error ? error.message : '加载文章失败'))
  }, [mode, postId, request])

  const autoGenerateDescription = () => {
    updateForm(
      'description',
      postForm.content
        .replace(/[\n\t]/g, ' ')
        .replace(/<[^>]*>/g, '')
        .replace(/&(nbsp|amp|quot|apos);/g, '')
        .slice(0, 150)
        .trim()
    )
  }

  const submit = async () => {
    if (!postForm.title || !postForm.alias || !postForm.content) {
      toast.warning('请填写标题、别名和内容')
      return
    }
    if ((postForm.tags_id?.length ?? 0) > 2) {
      toast.warning('最多选择 2 个标签')
      return
    }

    setPending(true)
    try {
      if (mode === 'create') {
        await createPostAPI(request, postForm)
        toast.success('发布成功')
      } else {
        await updatePostAPI(request, postForm)
        toast.success('编辑成功')
      }
      router.push('/admin/post/list?type=publish')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : '保存失败')
    } finally {
      setPending(false)
    }
  }

  return (
    <div className="flex flex-col gap-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-base font-semibold">{mode === 'create' ? '发布文章' : '编辑文章'}</h1>
            <Badge variant={postForm.is_publish ? 'default' : 'secondary'}>
              {postForm.is_publish ? '发布' : '草稿'}
            </Badge>
            {postForm.is_top && <Badge variant="secondary">置顶</Badge>}
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            Markdown 内容与发布配置会保存到现有后端接口。
          </p>
        </div>
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="outline">
              <SettingsIcon data-icon="inline-start" />
              发布配置
            </Button>
          </SheetTrigger>
          <SheetContent className="w-full overflow-y-auto sm:max-w-2xl">
            <SheetHeader>
              <SheetTitle>{mode === 'create' ? '发布文章' : '编辑文章'}</SheetTitle>
            </SheetHeader>
            <FieldGroup className="px-4 pb-4">
              <div className="grid gap-4 md:grid-cols-2">
                <Field>
                  <FieldLabel htmlFor="post-title">标题</FieldLabel>
                  <Input
                    id="post-title"
                    value={postForm.title}
                    maxLength={50}
                    onChange={event => updateForm('title', event.target.value)}
                  />
                </Field>
                <Field>
                  <FieldLabel htmlFor="post-alias">别名</FieldLabel>
                  <Input
                    id="post-alias"
                    value={postForm.alias}
                    onChange={event => updateForm('alias', event.target.value)}
                  />
                </Field>
              </div>
              <div className="grid gap-4 md:grid-cols-2">
                <Field>
                  <FieldLabel>分类</FieldLabel>
                  <Select
                    value={postForm.category_id || ''}
                    onValueChange={value => updateForm('category_id', value)}
                  >
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="请选择分类" />
                    </SelectTrigger>
                    <SelectContent position="popper">
                      <SelectGroup>
                        {categories.map(category => (
                          <SelectItem key={category.id} value={category.id}>
                            {category.name}
                          </SelectItem>
                        ))}
                      </SelectGroup>
                    </SelectContent>
                  </Select>
                </Field>
                <Field>
                  <FieldLabel htmlFor="post-created-at">发布时间</FieldLabel>
                  <Input
                    id="post-created-at"
                    type="datetime-local"
                    value={toDatetimeLocal(postForm.created_at)}
                    onChange={event =>
                      updateForm('created_at', new Date(event.target.value).toISOString())
                    }
                  />
                </Field>
              </div>
              <Field>
                <FieldLabel>标签</FieldLabel>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button type="button" variant="outline" className="w-full justify-between font-normal">
                      <span className={cn('truncate', !selectedTags.length && 'text-muted-foreground')}>
                        {selectedTagText}
                      </span>
                      <ChevronDownIcon data-icon="inline-end" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent
                    align="start"
                    className="max-h-72 w-[var(--radix-dropdown-menu-trigger-width)] overflow-y-auto"
                  >
                    <DropdownMenuLabel>最多选择 2 个标签</DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuGroup>
                      {tags.map(tag => {
                        const checked = postForm.tags_id?.includes(tag.id) ?? false
                        const disabled = !checked && (postForm.tags_id?.length ?? 0) >= 2

                        return (
                          <DropdownMenuCheckboxItem
                            key={tag.id}
                            checked={checked}
                            disabled={disabled}
                            onSelect={event => event.preventDefault()}
                            onCheckedChange={value => {
                              const current = postForm.tags_id ?? []
                              updateForm(
                                'tags_id',
                                value
                                  ? [...current, tag.id].slice(0, 2)
                                  : current.filter(id => id !== tag.id)
                              )
                            }}
                          >
                            {tag.name}
                          </DropdownMenuCheckboxItem>
                        )
                      })}
                    </DropdownMenuGroup>
                  </DropdownMenuContent>
                </DropdownMenu>
                {selectedTags.length ? (
                  <div className="flex flex-wrap gap-2">
                    {selectedTags.map(tag => (
                      <Badge key={tag.id} variant="secondary">
                        {tag.name}
                      </Badge>
                    ))}
                  </div>
                ) : null}
              </Field>
              <Field>
                <FieldLabel htmlFor="post-thumbnail">封面</FieldLabel>
                <Input
                  id="post-thumbnail"
                  value={postForm.thumbnail}
                  onChange={event => updateForm('thumbnail', event.target.value)}
                />
              </Field>
              <Field>
                <div className="flex items-center justify-between">
                  <FieldLabel htmlFor="post-description">描述</FieldLabel>
                  <div className="flex gap-2">
                    <Button type="button" variant="ghost" size="xs" onClick={autoGenerateDescription}>
                      自动截取
                    </Button>
                    <Button type="button" variant="ghost" size="xs" onClick={() => updateForm('description', '')}>
                      清空
                    </Button>
                  </div>
                </div>
                <Textarea
                  id="post-description"
                  value={postForm.description}
                  rows={4}
                  onChange={event => updateForm('description', event.target.value)}
                />
              </Field>
              <div className="flex flex-wrap gap-4">
                <label className="flex items-center gap-2 text-sm">
                  <Switch
                    checked={postForm.is_publish}
                    onCheckedChange={value => updateForm('is_publish', value)}
                  />
                  发布
                </label>
                <label className="flex items-center gap-2 text-sm">
                  <Switch checked={postForm.is_top} onCheckedChange={value => updateForm('is_top', value)} />
                  置顶
                </label>
              </div>
              <Button onClick={submit} disabled={pending}>
                <SaveIcon data-icon="inline-start" />
                {submitText}
              </Button>
            </FieldGroup>
          </SheetContent>
        </Sheet>
      </div>
      <div className="flex flex-col gap-4">
        <Field>
          <FieldLabel htmlFor="post-inline-title">标题</FieldLabel>
          <Input
            id="post-inline-title"
            value={postForm.title}
            maxLength={50}
            onChange={event => updateForm('title', event.target.value)}
            placeholder="请输入标题"
          />
        </Field>
        <AdminMarkdownEditor value={postForm.content} onChange={value => updateForm('content', value)} />
      </div>
    </div>
  )
}
